import { Footer } from "@/components/ui/footer";
import { Header } from "@/components/ui/header";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/ui/sidebar-cn";
import { getSiteConfig } from "@/lib/api";
import { ConfigProvider } from "@/providers/config";
import { SanityLive } from "@/sanity/live";
import type { Metadata } from "next";
import { VisualEditing } from "next-sanity/visual-editing";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies, draftMode } from "next/headers";
import "./globals.css";
import "./vendor/momo-yoga.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const config = await getSiteConfig();
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <ConfigProvider value={config}>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SidebarProvider defaultOpen={defaultOpen}>
            <AppSidebar />
            <main className="w-full">
              <Header
                title={config?.title}
                logo={config?.logo}
                menu={config?.menu}
                ctas={config?.ctas}
              />
              {children}
              <SanityLive />
              {(await draftMode()).isEnabled && <VisualEditing />}
              <Footer />
            </main>
          </SidebarProvider>
        </body>
      </html>
    </ConfigProvider>
  );
}
