import { Footer } from "@/components/ui/footer";
import { Header } from "@/components/ui/header";
import { getSiteConfig } from "@/lib/api";
import { SanityLive } from "@/sanity/live";
import type { Metadata } from "next";
import { VisualEditing } from "next-sanity/visual-editing";
import { Geist, Geist_Mono } from "next/font/google";
import { draftMode } from "next/headers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const config = await getSiteConfig();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header title={config.title} logo={config.logo} menu={config.menu} />
        {children}
        <SanityLive />
        {(await draftMode()).isEnabled && <VisualEditing />}
        <Footer />
      </body>
    </html>
  );
}
